version: '3'

services:

    # Nginx Container
    nginx:
        image: 'nginx:1.31'
        ports:
            - '80:80'
        volumes:
            - 'nginx_logs:/server_logs'
            - '.:/app'
            - './docker/nginx:/etc/nginx/conf.d'
        depends_on:
            - app
        restart: unless-stopped
        healthcheck:
            test: '/bin/bash service nginx status || exit 1'
            interval: 5s
            timeout: 1s
            retries: 5

    # MYSQL Container
    db:
        image: 'mysql:5.7'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=warehouse
            - MYSQL_USER=warehouse
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        restart: unless-stopped
        healthcheck:
            test: '/usr/bin/mysql --user=warehouse --password=secret --execute "SHOW DATABASES;"'
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/mysql

    # Warehouse App Container
    app:
        image: "ikea/warehouse:1.1.2"
        build: .
        command: 'gunicorn --bind 0.0.0.0:8000 app.wsgi'
        entrypoint: /entrypoint.sh
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=warehouse
            - DB_USERNAME=warehouse
            - DB_PASSWORD=secret
            - APP_URL=http://localhost
        volumes:
            - 'app_logs:/app/storage'
        depends_on:
            - db
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/_health"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db_data: null
    app_logs: null
    nginx_logs: null
