# Generated by Django 3.1.3 on 2020-11-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Identification')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'app_article',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60, verbose_name='ClientName')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PaidAmount')),
                ('currency', models.CharField(choices=[('EUR', 'EURO')], default='eur', max_length=10, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'app_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('EUR', 'EURO')], default='eur', max_length=10, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'app_product',
            },
        ),
        migrations.CreateModel(
            name='ProductArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_articles_amount', to='app.article', verbose_name='Related Article')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_articles_amount', to='app.product', verbose_name='Related Product')),
            ],
            options={
                'db_table': 'app_product_articles',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='articles',
            field=models.ManyToManyField(related_name='product', through='app.ProductArticles', to='app.Article'),
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Related Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Related Product')),
            ],
            options={
                'db_table': 'app_order_poducts',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', through='app.OrderProducts', to='app.Product'),
        ),
    ]
